[package]
name = "hs-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
log = "0.4"
env_logger = "0.11"
<<<<<<< HEAD
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "signal", "net", "io-util"] }

# Included per requirements; not used directly in this demo path.
hotstuff_rs = "0.4"
rand_core = "0.6"
base64 = "0.21"
borsh = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
axum = { version = "0.7", features = ["macros"] }
utoipa = { version = "4", features = ["axum_extras", "yaml", "uuid"] }
utoipa-swagger-ui = { version = "7", features = ["axum"] }
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
=======
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }

# Included per requirements; not used directly in this demo path.
hotstuff_rs = "0.4"

[profile.release]
opt-level = 3

>>>>>>> 5f9cdcd (Move demo into hotstuff/ subfolder and add root workspace manifest)
